example:
    property: I AM THE DEFAULT
spring:
    jpa:
        database: SQL_SERVER
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.SQLServerDialect
    datasource:
        url: jdbc:jtds:sqlserver://127.0.0.1;databaseName=Test
        username: ceci
        password: ceciits
        testWhileIdle: true
        validationQuery: SELECT 1